// <auto-generated />
using System;
using ECommerceApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727194647_SoruCevapEklendi")]
    partial class SoruCevapEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApi.Entities.DestekTalepleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminCevabi")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CevaplanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("DestekTalepleri");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Karturun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("SepetUrunleri");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UstKategoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Magaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IletisimTelefonu")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("MagazaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnaylandiMi")
                        .HasColumnType("boolean");

                    b.Property<double>("OrtalamaPuan")
                        .HasColumnType("double precision");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("Magazalar");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Oylama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<string>("YorumMetni")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Oylamalar");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeslimatAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KargoFirma")
                        .HasColumnType("text");

                    b.Property<string>("KargoTakipNo")
                        .HasColumnType("text");

                    b.Property<decimal>("PlatformKomisyonu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaticiKazanci")
                        .HasColumnType("numeric");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("ECommerceApi.Entities.UrunSoru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CevapMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CevapTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CevaplandiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SoruTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunSorulari");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Urunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AdminOnayliMi")
                        .HasColumnType("boolean");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("IndirimBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int>("MagazaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("text");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("MagazaId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.DestekTalepleri", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Favori", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Urunler", "Urunler")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Karturun", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Urunler", "Urunler")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Kategori", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId");

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Magaza", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanici")
                        .WithOne("Magaza")
                        .HasForeignKey("ECommerceApi.Entities.Magaza", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Oylama", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Urunler", "Urunler")
                        .WithMany("Oylamalar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Siparis", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ECommerceApi.Entities.SiparisDetay", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Siparis", "Siparis")
                        .WithMany("Detaylar")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Urunler", "Urunler")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.UrunSoru", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kullanicilar", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Urunler", "Urun")
                        .WithMany("Sorular")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Urunler", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Magaza", "Magaza")
                        .WithMany("Urunler")
                        .HasForeignKey("MagazaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Magaza");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Kullanicilar", b =>
                {
                    b.Navigation("Magaza");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Magaza", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Siparis", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Urunler", b =>
                {
                    b.Navigation("Oylamalar");

                    b.Navigation("Sorular");
                });
#pragma warning restore 612, 618
        }
    }
}
